# Customization of the appearance of the item.
items:
  invisible_item_frame:
    # What the name of the item should be.
    name: §rInvisible Item Frame
    # if the item should have an enchantment glint
    enchantment_glint: true

    # Uncomment to assign lore text for the item.
    #lore:
    #  - line1
    #  - line2

  invisible_glow_item_frame:
    name: §rInvisible Glow Item Frame
    enchantment_glint: true

# Customization for the crafting recipe.
recipes:
  invisible_item_frame:

    # Shape to use for crafting recipe. Spaces are empty slots, and for a smaller than 3x3 recipe you can use a smaller grid. Letters are interpreted by the ingredients list below.
    shape:
      - FFF
      - F F
      - FFF

    # Items that are required for crafting.
    ingredients:
      F: minecraft:item_frame

    # How many of the item should be produced by the recipe.
    count: 8

  invisible_glow_item_frame:
    shape:
      - FFF
      - F F
      - FFF
    ingredients:
      F: minecraft:glow_item_frame
    count: 8
