name: InvisibleItemFramesLite
version: ${project.version}
main: com.atlasgong.invisibleitemframeslite.InvisibleItemFramesLite
api-version: 1.16
description: Adds craftable invisible item frames for survival.
authors:
  - Tiffnix
  - atlasgong
website:
  - https://github.com/atlasgong/InvisibleItemFramesLite
